# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## !USE TEXT THEME
theme: jekyll-text-theme # Gem-based Jekyll Themes
# remote_theme: kitian616/jekyll-TeXt-theme # Jekyll Remote Theme, see https://github.com/benbalter/jekyll-remote-theme for more information.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'
## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
title: "FIT-NISSEN PT"
email: "info@fit-nissen.nl"
description: "Personal Training op maat – kracht, conditie & gezondheid"
baseurl: ""
url: "https://fit-nissen.nl"
logo: "/assets/logo.png"

nav:
  - title: "Home"
    url: /
  - title: "Over mij"
    url: /over/
  - title: "Training"
    url: /training/
  - title: "Contact"
    url: /contact/
